### ISSUE TITLE
parallel typescript tests are slower than serialized tests

### ISSUE THREAD

**Issue by Melvillian** [fvictorio/hardhat-examples#3]
I was excited to learn from this repo that hardhat mocha tests could be run in parallel! However, I tried the

```
npm install --dev mocha
npx mocha --require hardhat/register --extension ts --recursive --parallel --exit
```

command on several typescript hardhat projects I've worked on, and in both cases it resulted in either slower test suite runs, or tons of errors involving timeout errors. Is there something I'm missing when running my TS hardhat tests in parallel? For example, compare the runtimes of `npx hardhat test` and `npx mocha --require hardhat/register --extension ts --recursive --parallel --exit` for[ this repo](https://github.com/sirenmarkets/core)

**Comment by fvictorio** [comment]
Hey @Melvillian, sorry for taking so long to answer this.

Can you try prefixing your commands with `TS_NODE_TRANSPILE_ONLY=1` and check if that improves things?

**Comment by Melvillian** [comment]
That did speed things up, and it didn't help in my case, but after some more testing I think that's because of my code, and nothing to do with the mocha runner. Thank you!
